/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
 *
 * Generated on: 26-Sep-2011 16:24:48
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2011a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int DSP_FIRFilter_lp_fc_4_size = 11;
const real32_T DSP_FIRFilter_lp_fc_4[11] = {
               -0, -0.00713744713, -0.02127975598,  0.06046942249,   0.2704274952,
     0.3950406015,   0.2704274952,  0.06046942249, -0.02127975598, -0.00713744713,
               -0
};
