/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
 *
 * Generated on: 08-Nov-2011 16:32:15
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2011a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int DSP_FIRFilter_lp_fc_1_size = 11;
const real32_T DSP_FIRFilter_lp_fc_1[11] = {
   0.009967282414,  0.02486165985,  0.06683669239,   0.1248889416,   0.1755918562,
     0.1957071424,   0.1755918562,   0.1248889416,  0.06683669239,  0.02486165985,
   0.009967282414
};
