/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
 *
 * Generated on: 26-Sep-2011 16:25:50
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2011a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int DSP_FIRFilter_lp_fc_7_size = 11;
const real32_T DSP_FIRFilter_lp_fc_7[11] = {
               -0, 0.004469675943,  0.01133577246, -0.09913893789,   0.2330896109,
     0.7004877329,   0.2330896109, -0.09913893789,  0.01133577246, 0.004469675943,
               -0
};
